// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACjGxImtIGIpf3LbEXlh23zjxw0ZKzITE',
    appId: '1:814375922264:web:a4b1471cfd33e6b7fff82d',
    messagingSenderId: '814375922264',
    projectId: 'arise-c8cb7',
    authDomain: 'arise-c8cb7.firebaseapp.com',
    storageBucket: 'arise-c8cb7.firebasestorage.app',
    measurementId: 'G-FD3C3SNRPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3iXVx9iZHq6IfpJJBHnHkbwP30baYaiU',
    appId: '1:814375922264:android:b172e6f2e88e510dfff82d',
    messagingSenderId: '814375922264',
    projectId: 'arise-c8cb7',
    storageBucket: 'arise-c8cb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbzrQc_sSAR832-NR9z7sb3c46lfsAuis',
    appId: '1:814375922264:ios:2c609d5578e9fb53fff82d',
    messagingSenderId: '814375922264',
    projectId: 'arise-c8cb7',
    storageBucket: 'arise-c8cb7.firebasestorage.app',
    iosClientId: '814375922264-6j368e7fvlo45otb17v9mhke5qefpa7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.arise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbzrQc_sSAR832-NR9z7sb3c46lfsAuis',
    appId: '1:814375922264:ios:2c609d5578e9fb53fff82d',
    messagingSenderId: '814375922264',
    projectId: 'arise-c8cb7',
    storageBucket: 'arise-c8cb7.firebasestorage.app',
    iosClientId: '814375922264-6j368e7fvlo45otb17v9mhke5qefpa7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.arise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACjGxImtIGIpf3LbEXlh23zjxw0ZKzITE',
    appId: '1:814375922264:web:ff7a4a94f0754c79fff82d',
    messagingSenderId: '814375922264',
    projectId: 'arise-c8cb7',
    authDomain: 'arise-c8cb7.firebaseapp.com',
    storageBucket: 'arise-c8cb7.firebasestorage.app',
    measurementId: 'G-G4DHT8LWXG',
  );
}